### PR TITLE
Add loading spinner to list pages

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by kahboom** [comment]
Haven't tested locally, but looks good.. 👍

**Comment by jimmidyson** [comment]
Should we add screenshots for this stuff? gifs perhaps? Easy way to capture those?

**Comment by kahboom** [comment]
@jimmidyson - I use Chrome extensions for that, or just OSX/macOS Command + Shift + 4 for spot screenshots. The extensions I use are [Awesome Screenshot](https://chrome.google.com/webstore/detail/awesome-screenshot-screen/nlipoenfbbikpbjkfpfillcgkoblgpmj) for screenshots and [Openvid](https://chrome.google.com/webstore/detail/openvid-screen-recorder-c/liecbddmkiiihnedobmlmillhodjkdmb) for up to 5 minute long nicer screencasts (voice+video are optional). I used to also use [Screencastify](https://chrome.google.com/webstore/detail/screencastify-screen-vide/mmeijimgabbpbgpdklnllpncmdofkcpn) for quick animated screencasts. I'm sure they have these same extensions or similar for Firefox.

**Comment by jimmidyson** [comment]
Here you go - massive 1MB animated gif...

anim

**Comment by kahboom** [comment]
@jimmidyson - Cute! 👍

**Pull request merged**
