### PR TITLE
Add create and update to AbstractStore

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by jimmidyson** [comment]
Ping @jstrachan

**Comment by jimmidyson** [comment]
Once we have a nice error component then we should have an errors service that are updated from stuff like this.

**Comment by jstrachan** [comment]
lgtm [merge]

**Comment by kahboom** [comment]
@jimmidyson - Do you think there is a use case here for Delete in AbstractStore?

**Comment by jimmidyson** [comment]
Yep. Can you add it in please?

**Comment by kahboom** [comment]
Thanks, I figured. I'll create a separate issue for it.

**Pull request merged**
