### PR TITLE
lets add a spike at a routing doc

### PR DESCRIPTION
**Pull request by jstrachan**

### CODE REVIEW

**Comment by jimmidyson** [comment]
As this stuff is going to be common to all our angular2 development, I'd like to put this into a separate docs-only repo so it can be easily referenced, updated, published, etc. WDYT?

@kahboom Is this something you'd like to look after for us?

**Comment by jstrachan** [comment]
@jimmidyson sure, sounds good to me - lets make sure we clearly link to it from the contributing/readme files so folks don't lose it. Could also go into naming conventions for the various view/view-page/view-toolbar kinda stuff too maybe?

**Comment by jimmidyson** [comment]
> Could also go into naming conventions for the various view/view-page/view-toolbar kinda stuff too maybe?

Yeah we need to do that. For now, it's enough to just reference the Angular 2 style guide at https://angular.io/styleguide, but we can copy over what we need as we need it.

**Comment by jimmidyson** [comment]
I've created https://github.com/redhat-ipaas/ipaas-ui-style-guide using asciidoctor for documentation. Published on push to master branch to https://redhat-ipaas.github.io/ipaas-ui-style-guide/

**Pull request closed without merging**
